/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package syllabusmarker;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Mahe
 */
public class SyllabusMarker extends javax.swing.JFrame {

    File sylfile;

    /**
     * Creates new form SyllabusMarker
     */
    public SyllabusMarker() {
        initComponents();
        ListCellRenderer r = new ListCellRenderer() {

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel jj = new JLabel((String) value);
                jj.setOpaque(isSelected);
                if (isSelected) {
                    jj.setBackground(new Color(239, 239, 239));
                    jj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a (1).png")));
                } else {
                    jj.setBackground(Color.white);
                    jj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a (2).png")));
                }
                return jj;
            }
        };
        jList1.setCellRenderer(r);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        editSelected = new javax.swing.JMenuItem();
        doneCheck = new javax.swing.JMenuItem();
        doneUncheck = new javax.swing.JMenuItem();
        todoCheck = new javax.swing.JMenuItem();
        todoUncheck = new javax.swing.JMenuItem();
        deleteSelected = new javax.swing.JMenuItem();
        descDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        description = new javax.swing.JEditorPane();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        topicName = new javax.swing.JTextField();
        descDialog1 = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        description1 = new javax.swing.JEditorPane();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        topicName1 = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        sylname = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        dialog.setAlwaysOnTop(true);
        dialog.setLocationByPlatform(true);
        dialog.setMinimumSize(new java.awt.Dimension(500, 420));
        dialog.setModal(true);
        dialog.setType(java.awt.Window.Type.POPUP);

        jFileChooser1.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        jFileChooser1.setApproveButtonText("New");
        jFileChooser1.setDialogTitle("Create New VSF File :");
        jFileChooser1.setFileFilter(new VSFFilter());
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogLayout = new javax.swing.GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(dialogLayout);
        dialogLayout.setHorizontalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        dialogLayout.setVerticalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        editSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-find-replace.png"))); // NOI18N
        editSelected.setText("Edit Selected Items");
        editSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSelectedActionPerformed(evt);
            }
        });
        jPopupMenu1.add(editSelected);

        doneCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gtk-apply.png"))); // NOI18N
        doneCheck.setText("Check selected items as Done");
        doneCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneCheckActionPerformed(evt);
            }
        });
        jPopupMenu1.add(doneCheck);

        doneUncheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gtk-apply-no.png"))); // NOI18N
        doneUncheck.setText("Uncheck selected items as Not Done");
        doneUncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneUncheckActionPerformed(evt);
            }
        });
        jPopupMenu1.add(doneUncheck);

        todoCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a (1).png"))); // NOI18N
        todoCheck.setText("Check selected items to do");
        todoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoCheckActionPerformed(evt);
            }
        });
        jPopupMenu1.add(todoCheck);

        todoUncheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a (2).png"))); // NOI18N
        todoUncheck.setText("Uncheck selected items not to do");
        todoUncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoUncheckActionPerformed(evt);
            }
        });
        jPopupMenu1.add(todoUncheck);

        deleteSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gtk-dialog-error.png"))); // NOI18N
        deleteSelected.setText("Delete Selected Items");
        deleteSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedActionPerformed(evt);
            }
        });
        jPopupMenu1.add(deleteSelected);

        descDialog.setTitle("Add New Topic :");
        descDialog.setAlwaysOnTop(true);
        descDialog.setLocationByPlatform(true);
        descDialog.setMinimumSize(new java.awt.Dimension(400, 300));
        descDialog.setModal(true);
        descDialog.setType(java.awt.Window.Type.UTILITY);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        description.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(description);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Submit");
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Topic Name :");

        topicName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout descDialogLayout = new javax.swing.GroupLayout(descDialog.getContentPane());
        descDialog.getContentPane().setLayout(descDialogLayout);
        descDialogLayout.setHorizontalGroup(
            descDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(descDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topicName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton2))
        );
        descDialogLayout.setVerticalGroup(
            descDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descDialogLayout.createSequentialGroup()
                .addGroup(descDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(descDialogLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(descDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(topicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        descDialog1.setTitle("Edit Topic :");
        descDialog1.setAlwaysOnTop(true);
        descDialog1.setLocationByPlatform(true);
        descDialog1.setMinimumSize(new java.awt.Dimension(420, 300));
        descDialog1.setModal(true);
        descDialog1.setType(java.awt.Window.Type.UTILITY);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        description1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jScrollPane4.setViewportView(description1);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Change");
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Edit Topic Name :");

        topicName1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout descDialog1Layout = new javax.swing.GroupLayout(descDialog1.getContentPane());
        descDialog1.getContentPane().setLayout(descDialog1Layout);
        descDialog1Layout.setHorizontalGroup(
            descDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(descDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topicName1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton3))
        );
        descDialog1Layout.setVerticalGroup(
            descDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descDialog1Layout.createSequentialGroup()
                .addGroup(descDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(descDialog1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(descDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(topicName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virtual Syllabus Manager");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/12.png")).getImage());
        setIconImages(null);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 400));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Progress :");
        jToolBar1.add(jLabel2);
        jToolBar1.add(jProgressBar1);

        sylname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        sylname.setText("Syllabus Name :");
        jToolBar1.add(sylname);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jList1.setComponentPopupMenu(jPopupMenu1);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Topic Name :");
        jToolBar2.add(jLabel1);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jToolBar2.add(jTextField1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setText("Press Enter OR Click Here To Add Description");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Topic List", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane2.setViewportView(jPanel1);

        jTabbedPane1.addTab("Topic View", jScrollPane2);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 25));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 25));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document-new.png"))); // NOI18N
        jMenuItem1.setText("New Virtual Syllabus");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document-open_normal.png"))); // NOI18N
        jMenuItem2.setText("Open Virtual Syllabus");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document-save.png"))); // NOI18N
        jMenuItem3.setText("Save Virtual Syllabus");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document-save-as.png"))); // NOI18N
        jMenuItem4.setText("Save Virtual Syllabus As");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator2);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application-exit.png"))); // NOI18N
        jMenuItem8.setText("Exit");
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gtk-add.png"))); // NOI18N
        jMenuItem5.setText("Add Topic");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (jTextField1.getText().length() != 0) {
                Topic t = new Topic();
                t.setTopic(jTextField1.getText(), true, false);
                t.setBounds(0, 0, 400, 80);
                t.setVisible(true);

                topics.add(t);

                DefaultListModel d = new DefaultListModel();
                for (int i = 0; i < jList1.getModel().getSize(); i++) {
                    d.addElement(jList1.getModel().getElementAt(i));
                }
                d.addElement(t.getTopic());
                jList1.setModel(d);
            } else if (jTextField1.getText().equals("")) {
                jTextField1.setText("Topic?");
            }

            this.repaint();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        descDialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        int done = 0;
        for (int i = 0; i < topics.size(); i++) {
            if (topics.get(i).getDoneStatus()) {
                done++;
            }
        }
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(topics.size());
        jProgressBar1.setValue(done);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        showDialog('n');
        jList1.setModel(new DefaultListModel());
        topics.clear();
        this.repaint();
        sylname.setText("Syllabus Name : ");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        showDialog('o');
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        String s = (evt.paramString().toUpperCase());
        if (s.contains("APPROVE")) {
            String ss = jFileChooser1.getApproveButtonText();
            if (jFileChooser1.getDialogType() == javax.swing.JFileChooser.OPEN_DIALOG) {
                sylfile = jFileChooser1.getSelectedFile();
                load(sylfile);
                dialog.hide();
                System.out.println("Open");
            } else if (jFileChooser1.getDialogType() == javax.swing.JFileChooser.SAVE_DIALOG) {
                sylfile = jFileChooser1.getSelectedFile();
                saveTo(sylfile);
                dialog.hide();
                System.out.println("Save");
            } else if (jFileChooser1.getApproveButtonText().equals("Create")) {
                sylfile = jFileChooser1.getSelectedFile();
                sylname.setText(sylfile.getName());
                dialog.hide();
                System.out.println("Create");
            }
        } else if (s.contains("CANCEL")) {
            dialog.hide();
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (sylfile == null) {
            showDialog('s');
        } else {
            saveTo(sylfile);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        showDialog('s');
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void doneCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneCheckActionPerformed
        // TODO add your handling code here:
        int[] a = jList1.getSelectedIndices();
        for (int i = 0; i < a.length; i++) {
            topics.get(a[i]).setDone(true);
            topics.get(a[i]).repaint();
        }
        this.repaint();
    }//GEN-LAST:event_doneCheckActionPerformed

    private void deleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedActionPerformed
        // TODO add your handling code here:
        int a[] = jList1.getSelectedIndices();
        DefaultListModel d = new DefaultListModel();
        for (int i = 0; i < jList1.getModel().getSize(); i++) {
            d.addElement(jList1.getModel().getElementAt(i));
        }
        for (int i = 0; i < a.length; i++) {
            d.remove(a[i]);
            topics.remove(a[i]);
        }
        jList1.setModel(d);
        this.repaint();
    }//GEN-LAST:event_deleteSelectedActionPerformed

    private void doneUncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneUncheckActionPerformed
        // TODO add your handling code here:
        int[] a = jList1.getSelectedIndices();
        for (int i = 0; i < a.length; i++) {
            topics.get(a[i]).setDone(false);
            topics.get(a[i]).repaint();
        }
        this.repaint();
    }//GEN-LAST:event_doneUncheckActionPerformed

    private void todoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoCheckActionPerformed
        // TODO add your handling code here:
        int[] a = jList1.getSelectedIndices();
        for (int i = 0; i < a.length; i++) {
            topics.get(a[i]).setTodo(true);
            topics.get(a[i]).repaint();
        }
        this.repaint();
    }//GEN-LAST:event_todoCheckActionPerformed

    private void todoUncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoUncheckActionPerformed
        // TODO add your handling code here:
        int[] a = jList1.getSelectedIndices();
        for (int i = 0; i < a.length; i++) {
            topics.get(a[i]).setTodo(false);
            topics.get(a[i]).repaint();
        }
        this.repaint();
    }//GEN-LAST:event_todoUncheckActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (topicName.getText().length() != 0) {
            Topic t = new Topic();
            t.setTopic("<html><b>" + topicName.getText() + "</b>" + description.getText(), true, false);
            t.setBounds(0, 0, 400, 80);
            t.setVisible(true);

            topics.add(t);

            DefaultListModel d = new DefaultListModel();
            for (int i = 0; i < jList1.getModel().getSize(); i++) {
                d.addElement(jList1.getModel().getElementAt(i));
            }
            d.addElement(t.getTopic());
            jList1.setModel(d);
        } else if (topicName.getText().equals("")) {
            topicName.setText("Topic?");
        }

        this.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        descDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Topic nt = new Topic();
        System.out.println(idx);
        nt.setTopic("<html><b>" + topicName1.getText() + "</b>" + description1.getText(), topics.get(idx).getTodo(), topics.get(idx).getDone());
        nt.setBounds(0, 0, 400, 80);
        nt.setVisible(true);
        DefaultListModel d = new DefaultListModel();
        Topic[] arr = new Topic[topics.size()];
        for (int i = 0; i < topics.size(); i++) {
            arr[i] = topics.remove(0);
        }
        System.out.println("Removing and Replacing At : " + idx);
        arr[idx] = nt;
        for (int i = 0; i < arr.length; i++) {
            topics.add(arr[i]);
        }
        for (int i = 0; i < topics.size(); i++) {
            d.addElement(topics.get(i).getTopic());
        }
        topics.clear();
        jList1.setModel(d);
    }//GEN-LAST:event_jButton3ActionPerformed
    int idx;
    private void editSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSelectedActionPerformed
        // TODO add your handling code here:
        System.out.println("Selected index : " + idx);
        String s = topics.get(idx).getTopic();
        String as = "";
        System.out.println("Editing : " + as + "\n\t" + s);
        if (s.contains("<b>")) {
            as = s.substring(s.indexOf("<b>") + 3, s.indexOf("</b>"));
            topicName1.setText(as);
            description1.setText(s.substring(s.indexOf("</b>") + 4));
        } else {
            topicName1.setText(s);
        }
        idx = jList1.getSelectedIndex();
        descDialog1.setVisible(true);
    }//GEN-LAST:event_editSelectedActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        System.out.println("LOL > " + jList1.getSelectedIndex());
    }//GEN-LAST:event_jList1ValueChanged
    Vector<Topic> topics = new Vector<Topic>();

    @Override
    public void repaint() {
        super.repaint(); //To change body of generated methods, choose Tools | Templates.
        jPanel1.removeAll();
        for (int i = 0; i < topics.size(); i++) {
            jPanel1.add(topics.get(i));
        }
        jPanel1.repaint();
        if (jList1.getModel().getSize() == 0) {
            editSelected.setEnabled(false);
            doneCheck.setEnabled(false);
            doneUncheck.setEnabled(false);
            todoCheck.setEnabled(false);
            todoUncheck.setEnabled(false);
            deleteSelected.setEnabled(false);
        } else {
            editSelected.setEnabled(true);
            doneCheck.setEnabled(true);
            doneUncheck.setEnabled(true);
            todoCheck.setEnabled(true);
            todoUncheck.setEnabled(true);
            deleteSelected.setEnabled(true);
        }
        if (topics.size() == 0) {
            if (jList1.getModel().getSize() != 0) {
                jList1.setModel(new DefaultListModel());
            }
        }
        super.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SyllabusMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SyllabusMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SyllabusMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SyllabusMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        if (args != null) {
            System.out.println("Reading Params");
            for (int i = 0; i < args.length; i++) {
                final String f = args[i];
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        SyllabusMarker s = new SyllabusMarker();
                        s.setVisible(true);
                        s.open(f);
                    }
                });
            }
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SyllabusMarker().setVisible(true);
            }
        });
    }

    public void showDialog(char purpose) {
        //o - open, s - save, n - new
        if (purpose == 'n') {
            jFileChooser1.setApproveButtonText("Create");
            jFileChooser1.setDialogTitle("New VSF File :");
            dialog.setTitle("New VSF File :");
            jFileChooser1.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        } else if (purpose == 'o') {
            jFileChooser1.setApproveButtonText("Open");
            jFileChooser1.setDialogTitle("Open VSF File :");
            dialog.setTitle("Open VSF File :");
            jFileChooser1.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
        } else if (purpose == 's') {
            jFileChooser1.setApproveButtonText("Create");
            jFileChooser1.setDialogTitle("New VSF File :");
            dialog.setTitle("New VSF File :");
            jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        }
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem deleteSelected;
    private javax.swing.JDialog descDialog;
    private javax.swing.JDialog descDialog1;
    private javax.swing.JEditorPane description;
    private javax.swing.JEditorPane description1;
    private javax.swing.JDialog dialog;
    private javax.swing.JMenuItem doneCheck;
    private javax.swing.JMenuItem doneUncheck;
    private javax.swing.JMenuItem editSelected;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel sylname;
    private javax.swing.JMenuItem todoCheck;
    private javax.swing.JMenuItem todoUncheck;
    private javax.swing.JTextField topicName;
    private javax.swing.JTextField topicName1;
    // End of variables declaration//GEN-END:variables

    public void write(File f, String s) {
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(new FileWriter(f));
            pw.write(s);
            pw.close();
        } catch (IOException ex) {
            Logger.getLogger(SyllabusMarker.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            pw.close();
        }
    }

    public void append(File f, String s) {
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(new FileWriter(f, true));
            pw.write(s);
            pw.close();
        } catch (IOException ex) {
            Logger.getLogger(SyllabusMarker.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            pw.close();
        }
    }

    public String read(File f) {
        String ss = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader(f));
            String s = "";
            while ((s = br.readLine()) != null) {
                ss += s + "\n";
            }
            br.close();
        } catch (IOException ex) {
        }
        return ss;
    }

    private void load(File sylfile) {
        topics.clear();
        String s = read(sylfile);
        String name = s.substring(s.indexOf("[sylname=") + 9, s.indexOf("]"));
        sylname.setText("Syllabus Name : " + name);
        String list = s.substring(s.indexOf("]") + 1);
        StringTokenizer st = new StringTokenizer(list, "|");
        int n = st.countTokens();
        DefaultListModel d = new DefaultListModel();
        int ci = list.indexOf("[");
        int ci2 = list.indexOf("]");
        while (ci != -1 && ci2 != -1) {
            String a = list.substring(ci + 1, ci2);
            ci = list.indexOf("[", ci + 1);
            ci2 = list.indexOf("]", ci2 + 1);
            int iu1 = a.indexOf(":");
            int iu2 = a.indexOf(":", iu1 + 1);
            String todos = a.substring(0, iu1);
            String dones = a.substring(iu1 + 1, iu2);
            String contents = a.substring(iu2 + 1);
            Topic t = new Topic();
            t.setTopic(contents, todos.charAt(0) != 'n', dones.charAt(0) != 'n');
            t.setBounds(0, 0, 400, 80);
            t.setVisible(true);
            topics.add(t);
            d.addElement(contents);
        }
        jList1.setModel(d);
        this.repaint();
    }

    private void saveTo(File sylfile) {
        System.out.println(sylfile.getName());
        String name = sylfile.getName();
        if (name.endsWith(".vsf") && name.lastIndexOf(".") != -1) {
            name = name.substring(0, name.lastIndexOf("."));
        }
        String towrite = "[sylname=" + name + "]";
        for (int i = 0; i < topics.size(); i++) {
            String ss = (String) jList1.getModel().getElementAt(i);
            char todo = (topics.get(i).getTodo()) ? 'y' : 'n';
            char done = (topics.get(i).getDone()) ? 'y' : 'n';
            towrite = towrite + "[" + todo + ":" + done + ":" + ss + "]";
        }
        write(sylfile, towrite);
    }

    private void open(String string) {
        File f = new File(string);
        if(f.exists()) {
            sylfile = f;
            load(f);
        } else {
            showDialog('o');
        }
    }
}
